# Generated by Django 6.0.3 on 2026-03-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celebrity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('bio', models.TextField(verbose_name='Биография')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
            ],
        ),
    ]
