# Generated by Django 6.0.3 on 2026-03-14 12:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebrity',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='celebrity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='celebrity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
