# Generated by Django 6.0.3 on 2026-03-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrities', '0002_celebrity_content_celebrity_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celebrity',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
