# Generated by Django 6.0.3 on 2026-03-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrities', '0003_alter_celebrity_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebrity',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
