# Generated by Django 6.0.3 on 2026-03-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrities', '0004_celebrity_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celebrity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='celebs'),
        ),
    ]
