# Generated by Django 6.0.3 on 2026-03-15 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrities', '0005_alter_celebrity_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cetegory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='celebrity',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='celebrities.cetegory'),
        ),
    ]
