# Generated by Django 6.0.3 on 2026-03-15 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celebrities', '0006_cetegory_celebrity_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='celebrity',
            old_name='category',
            new_name='cetegory',
        ),
    ]
