# Generated by Django 6.0.3 on 2026-03-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrities', '0007_rename_category_celebrity_cetegory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='celebrity',
            name='tegs',
            field=models.ManyToManyField(to='celebrities.teg'),
        ),
    ]
