# Generated by Django 6.0.3 on 2026-03-18 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celebrities', '0008_teg_celebrity_tegs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cetegory',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Teg',
            new_name='Tag',
        ),
    ]
